name: CI
'on':
  push:
    branches:
      - master
jobs:
  about:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Jaid/action-sync-node-meta
        uses: jaid/action-sync-node-meta@v1.4.0
        with:
          direction: overwrite-github
          githubToken: '${{ secrets.GITHUB }}'
  
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/npm
            @semantic-release/git
            @semantic-release/github
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'
    outputs:
      new_release_published: '${{ steps.semantic.outputs.new_release_published }}'
      new_release_version: '${{ steps.semantic.outputs.new_release_version }}'
  
  cdn:
    runs-on: ubuntu-latest
    needs: release
    if: needs.release.outputs.new_release_published == 'true'
    env:
      VERSION: '${{ needs.release.outputs.new_release_version }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 14.15.4
      - name: yarn install
        run: >
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >
          .npmrc

          yarn install
      - name: yarn build
        run: yarn build
      - name: upload bundle
        uses: CoCreate-app/CoCreate-s3@master
        with:
          aws-key-id: '${{ secrets.AWSACCESSKEYID }}'
          aws-access-key: '${{ secrets.AWSSECERTACCESSKEY }}'
          bucket: testcrudbucket
          source: ./dist
          destination: '/${{env.VERSION}}'
          acl: public-read
